### ISSUE TITLE
open_position failed: custom program error: 0x1773

### ISSUE THREAD

**Issue by foonsun** [drift-labs/drift-py#3]
Hi Team. The error occurs when opening positions. I want to know the reason.thanks.

Traceback (most recent call last):
    open_position_response = await send_open_position(
  File "/drift/sdk/sends/asynchronous.py", line 204, in send_open_position
    rpc_response = await sign_and_send_transaction_instructions(
  File "/drift/sdk/sends/asynchronous.py", line 27, in sign_and_send_transaction_instructions
    response = await client.send_transaction(
  File "/data/pyenv/lib/python3.9/site-packages/solana/rpc/async_api.py", line 1069, in send_transaction
    txn_resp = await self.send_raw_transaction(txn.serialize(), opts=opts)
  File "/data/pyenv/lib/python3.9/site-packages/solana/rpc/async_api.py", line 1025, in send_raw_transaction
    return self._post_send(resp)
  File "/data/pyenv/lib/python3.9/site-packages/solana/rpc/core.py", line 374, in _post_send
    raise RPCException(maybe_error)
solana.rpc.core.RPCException: {'code': -32002, 'message': 'Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1773', 'data': {'accounts': None, 'err': {'InstructionError': [0, {'Custom': 6003}]}, 'logs': ['Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN invoke [1]', 'Program log: Instruction: OpenPosition', 'Program log: Custom program error: 0x1773', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN consumed 36895 of 200000 compute units', 'Program dammHkt7jmytvbS3nHTxQNEcP59aE57nxwV21YdqEDN failed: custom program error: 0x1773']}}

**Comment by foonsun** [comment]
solved.
